### ISSUE TITLE
Zwrot do czytelnika

### ISSUE THREAD

**Issue by MarekGubiec** [debian-handbook-pl/pl-PL#12]
Piszemy bezosobowo / na ty / na "Państwo" / etc.?
> CC @debian-handbook-pl/translators

**Comment by mateunho** [comment]
@captainBomb: W różnych podręcznikach różnie się tłumaczy. Trzeba jednak pamiętać, że my tłumaczymy Ten podręcznik, więc tekst powinien być zbieżny z oryginałem.
- W ogóle: należy tłumaczyć bezosobowo, bo jest to tekst z grubsza techniczny.
- W szczególności: występują fragmenty, w których autor zwraca się bezpośrednio do czytelnika (np. rozdziały 00a i 00b), więc należy je tłumaczyć "na ty".

Jeżeli tłumacz ma problem z określeniem jakiej formy użyć (choć wątpię :wink:), to należy użyć formy bezosobowej i ewentualnie zaznaczyć tłumaczenie jako niepewne (fuzzy).
