### ISSUE TITLE
Fix XML tags in chapter 7

### ISSUE THREAD

**Issue by mateunho** [debian-handbook-pl/pl-PL#66]
Refers to build break caused by improper tags.

**Comment by MarekGubiec** [comment]
I'm aware of the issue, will fix tonight or tomorrow.

2015-02-20 16:54 GMT+01:00 Mateusz Kacprzak notifications@github.com:

**Comment by MarekGubiec** [comment]
The file I pulled from the repo appears to be broken. This stuff will eventually take more than I thought. BTW could you provide me with building error logs so I can know where to look?

**Comment by mateunho** [comment]
Help yourself.

```
not well-formed (invalid token) at line 4, column 156, byte 320:
<!DOCTYPE para PUBLIC "-//OASIS//DTD DocBook XML V4.5//EN" "http://www.oasis-open.org/docbook/xml/4.5/docbookx.dtd" [
]>
<para processed="1">Wszystkie przykłady muszą być zainstalowane w katalogu  <filename>/usr/share/doc/<replaceable>paczka</replaceable>/examples/</filename. Może to być plik konfiguracyjny, kod źródłowy programu ( przykład użycia biblioteki ), albo skrypt konwertujący dane który może być użyty przez administratora w szczególnych wypadkach ( takich jak inicjowanie bazy danych ). Jeśli przykład jest specyficzny dla szczególnej architektury, powinien być zainstalowany w <filename>/usr/lib/<replaceable>paczka</replaceable>/examples/</filename> oraz powienien istnieć link wskazujący do tego pliku w katalogu <filename>/usr/share/doc/<replaceable>package</replaceable>/examples/</filename>.</para>
===========================================================================================================================================================^
 at /usr/lib/perl5/XML/Parser.pm line 187.
```

> Actually, build breaks after _first_ error, so log may not be so helpfull.
> If you want, just clone the upstream repo and build yourself
> `git clone https://alioth.debian.org/anonscm/git/debian-handbook/debian-handbook.git wheezy/master` and then `./build/build-html` (but make sure to build pl-PL)

**Comment by mateunho** [comment]
What do you mean by

> appears to be broken

?

**Comment by MarekGubiec** [comment]
Halves of already previously translated paragraphs are missing. Chill out, I'll resolve this, I just need to get some time on my hands :P

**Comment by mateunho** [comment]
Chill out, it's only git. If those translated para's were committed somewhere/sometime, then they're not lost.

> Try switching to temporary branch and cherry-pick what you need.

**Comment by mateunho** [comment]
Great job:exclamation:
