### ISSUE TITLE
(Mini) słownik referencyjny Debiana

### ISSUE THREAD

**Issue by ghost** [debian-handbook-pl/pl-PL#94]
Tutaj można dodawać często stosowane terminy i ich tłumaczenia. Z założenia, ma to być słownik modyfikowany w miarę potrzeb. Proszę wpisywać terminy, które mogą mieć alternatywne znaczenia; porządek alfabetyczny jest mile widziany. Na razie, wpisałem tylko litery alfabetu. Mam nadzieję, że ten (mini) słownik będzie się z czasem rozrastał. Forma graficzna nie musi być perfekcyjna -- sam układ też poddaję pod dyskusję. Chodzi mi tylko o to, aby wszystkie terminy były w jednym miejscu. 

Jeśli ktoś potrafiłby z tego (w przyszłości) zrobić **przeszukiwalną bazę danych**, i jeśli taka baza mogłaby **poprawnie funkcjonować na GitHubie** (w naszym projekcie), to byłaby sytuacja idealna. Na razie, to co napisałem to tylko propozycja -- czekam na komentarze.

**A**

**B**

**C**

**D**

**E**

**F**

**G**

**H**

**I**

**J**

**K**

**M**

**N**

**O**

**P**

**Q**

**R**

**S**

**T**

**U**

**V**

**W**

**X**

**Y**

**Z**

**Comment by mateunho** [comment]
@stpk007, a może by tak przenieść to na Wiki?

**Comment by mateunho** [comment]
Poza tym istnieje już zgłoszenie w tym temacie: #70 
W związku z tym zamykam.

**Comment by ghost** [comment]
On Sat, November 26, 2016 20:17, Mateusz Kacprzak wrote:
> @stpk007, a może by tak przenieść to na Wiki?

Można, czemu nie, to była tylko propozycja.
